# Generated by Django 4.0.1 on 2022-10-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('setting', models.CharField(max_length=255)),
                ('mqttuser', models.CharField(max_length=255)),
                ('mqttpass', models.CharField(max_length=255)),
            ],
        ),
    ]
