# Generated by Django 4.0.1 on 2022-10-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userregister_remove_device_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nordpool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Hour', models.CharField(max_length=255)),
                ('SYS', models.FloatField(max_length=255)),
                ('SE1', models.FloatField(max_length=255)),
                ('SE2', models.FloatField(max_length=255)),
                ('SE3', models.FloatField(max_length=255)),
                ('SE4', models.FloatField(max_length=255)),
                ('FI', models.FloatField(max_length=255)),
                ('DK1', models.FloatField(max_length=255)),
                ('DK2', models.FloatField(max_length=255)),
                ('Oslo', models.FloatField(max_length=255)),
                ('Kr_sand', models.FloatField(max_length=255)),
                ('Bergen', models.FloatField(max_length=255)),
                ('Molde', models.FloatField(max_length=255)),
                ('TR_heim', models.FloatField(max_length=255)),
                ('Tromso', models.FloatField(max_length=255)),
                ('EE', models.FloatField(max_length=255)),
                ('LV', models.FloatField(max_length=255)),
                ('LT', models.FloatField(max_length=255)),
                ('AT', models.FloatField(max_length=255)),
                ('BE', models.FloatField(max_length=255)),
                ('DE_LU', models.FloatField(max_length=255)),
                ('FR', models.FloatField(max_length=255)),
                ('NL', models.FloatField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
