# Generated by Django 4.0.1 on 2022-10-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nordpool_delete_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(default='user1', max_length=255),
            preserve_default=False,
        ),
    ]
